return {
	descriptions = {
		Back = {},
		Blind = {},
		Edition = {},
		Enhanced = {},
		Joker = {
			j_blueatro_sobface = {
				name = "Sobbing Face",
				text = {
					"If all scored cards are",
					"{C:attention}7{} or below, {C:mult}+#1#{} Mult",
				},
			},
			j_blueatro_teabagging = {
				name = "Teabagging",
				text = {
					"Whenever a card or",
					"Joker is destroyed,",
					"this gains {C:mult}+#2#{} Mult",
					"{C:inactive}(Currently {C:mult}+#1#{C:inactive} Mult)",
				},
			},
			j_blueatro_rollcake = {
				name = "Roll Cake",
				text = {
					"Creates a {C:planet}Planet{} card for",
					"the third played {C:attention}poker hand{}",
					"{C:inactive}({C:attention}#2#{C:attention} {C:inactive}hands played this round)",
					"{C:inactive}({C:attention}#1#{C:attention} {C:inactive}uses left)",
				},
			},
		},
		Other = {},
		Planet = {},
		Spectral = {},
		Stake = {},
		Tag = {},
		Tarot = {},
		Voucher = {},
	},
	misc = {
		achievement_descriptions = {},
		achievement_names = {},
		blind_states = {},
		challenge_names = {},
		collabs = {},
		dictionary = {},
		high_scores = {},
		labels = {},
		poker_hand_descriptions = {},
		poker_hands = {},
		quips = {},
		ranks = {},
		suits_plural = {},
		suits_singular = {},
		tutorial = {},
		v_dictionary = {},
		v_text = {},
	},
}
