[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self.removed = true"
position = "after"
match_indent = true
payload = '''
if next(find_card("ba_teabag")) then
	sendTraceMessage("Found a card")
	for _, v in pairs(find_card("ba_teabag")) do
		v.ability.extra.mult = v.ability.extra.mult + v.ability.extra.mult_gain
		card_eval_status_text(v, 'extra', nil, nil, nil,
			{message = localize({ type = "variable", key = "a_mult", vars = { v.ability.extra.mult }})}
		)
	end
end
'''
